// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import { PermissionLevel as __PermissionLevel } from "./permission_level_type";

export type AddGroupMember = {
  groupId: bigint,
  userIdentity: Identity,
  permissionLevel: __PermissionLevel,
};

/**
 * A namespace for generated helper functions.
 */
export namespace AddGroupMember {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("userIdentity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("permissionLevel", __PermissionLevel.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: AddGroupMember): void {
    AddGroupMember.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): AddGroupMember {
    return AddGroupMember.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

