// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { DiscoveryEvent } from "./discovery_event_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `discovery_event`.
 *
 * Obtain a handle from the [`discoveryEvent`] property on [`RemoteTables`],
 * like `ctx.db.discoveryEvent`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.discoveryEvent.on_insert(...)`.
 */
export class DiscoveryEventTableHandle {
  tableCache: TableCache<DiscoveryEvent>;

  constructor(tableCache: TableCache<DiscoveryEvent>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DiscoveryEvent> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `event_id` unique index on the table `discovery_event`,
   * which allows point queries on the field of the same name
   * via the [`DiscoveryEventEventIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.discoveryEvent.event_id().find(...)`.
   *
   * Get a handle on the `event_id` unique index on the table `discovery_event`.
   */
  event_id = {
    // Find the subscribed row whose `event_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): DiscoveryEvent | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.event_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DiscoveryEvent) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DiscoveryEvent) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DiscoveryEvent) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DiscoveryEvent) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DiscoveryEvent, newRow: DiscoveryEvent) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DiscoveryEvent, newRow: DiscoveryEvent) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
