// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type LiveFlight = {
  flightId: string,
  eventId: bigint | undefined,
  subEventId: bigint | undefined,
  signupId: bigint | undefined,
  userIdentity: Identity | undefined,
  groupId: bigint | undefined,
  callsign: string,
  aircraftId: string,
  liveryId: string,
  latitude: number,
  longitude: number,
  altitude: number,
  heading: number,
  groundSpeed: number,
  lastUpdated: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace LiveFlight {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("flightId", AlgebraicType.createStringType()),
      new ProductTypeElement("eventId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("subEventId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("signupId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("userIdentity", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("groupId", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("callsign", AlgebraicType.createStringType()),
      new ProductTypeElement("aircraftId", AlgebraicType.createStringType()),
      new ProductTypeElement("liveryId", AlgebraicType.createStringType()),
      new ProductTypeElement("latitude", AlgebraicType.createF64Type()),
      new ProductTypeElement("longitude", AlgebraicType.createF64Type()),
      new ProductTypeElement("altitude", AlgebraicType.createI32Type()),
      new ProductTypeElement("heading", AlgebraicType.createU16Type()),
      new ProductTypeElement("groundSpeed", AlgebraicType.createU16Type()),
      new ProductTypeElement("lastUpdated", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: LiveFlight): void {
    LiveFlight.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): LiveFlight {
    return LiveFlight.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


