// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import { EventStatus as __EventStatus } from "./event_status_type";

export type UpdateEvent = {
  eventId: bigint,
  name: string,
  description: string,
  startTime: Timestamp,
  endTime: Timestamp,
  ifcEventLink: string | undefined,
  bannerUrl: string | undefined,
  status: __EventStatus,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpdateEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("eventId", AlgebraicType.createU64Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("startTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("endTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("ifcEventLink", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("bannerUrl", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("status", __EventStatus.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UpdateEvent): void {
    UpdateEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UpdateEvent {
    return UpdateEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

