// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { SubEventData as __SubEventData } from "./sub_event_data_type";

export type CreateEvent = {
  creatorGroupId: bigint,
  name: string,
  description: string,
  startTime: Timestamp,
  endTime: Timestamp,
  ifcEventLink: string | undefined,
  bannerUrl: string | undefined,
  subEventsData: __SubEventData[],
};

/**
 * A namespace for generated helper functions.
 */
export namespace CreateEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("creatorGroupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("startTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("endTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("ifcEventLink", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("bannerUrl", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("subEventsData", AlgebraicType.createArrayType(__SubEventData.getTypeScriptAlgebraicType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: CreateEvent): void {
    CreateEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): CreateEvent {
    return CreateEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

