// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { DiscoveryRotationSchedule } from "./discovery_rotation_schedule_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `discovery_rotation_schedule`.
 *
 * Obtain a handle from the [`discoveryRotationSchedule`] property on [`RemoteTables`],
 * like `ctx.db.discoveryRotationSchedule`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.discoveryRotationSchedule.on_insert(...)`.
 */
export class DiscoveryRotationScheduleTableHandle {
  tableCache: TableCache<DiscoveryRotationSchedule>;

  constructor(tableCache: TableCache<DiscoveryRotationSchedule>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<DiscoveryRotationSchedule> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `scheduled_id` unique index on the table `discovery_rotation_schedule`,
   * which allows point queries on the field of the same name
   * via the [`DiscoveryRotationScheduleScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.discoveryRotationSchedule.scheduled_id().find(...)`.
   *
   * Get a handle on the `scheduled_id` unique index on the table `discovery_rotation_schedule`.
   */
  scheduled_id = {
    // Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): DiscoveryRotationSchedule | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduled_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: DiscoveryRotationSchedule, newRow: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: DiscoveryRotationSchedule, newRow: DiscoveryRotationSchedule) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
