// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace EventStatus {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Draft = { tag: "Draft" };
  export type Published = { tag: "Published" };
  export type InProgress = { tag: "InProgress" };
  export type Completed = { tag: "Completed" };
  export type Cancelled = { tag: "Cancelled" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Draft = { tag: "Draft" };
  export const Published = { tag: "Published" };
  export const InProgress = { tag: "InProgress" };
  export const Completed = { tag: "Completed" };
  export const Cancelled = { tag: "Cancelled" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Draft", AlgebraicType.createProductType([])),
      new SumTypeVariant("Published", AlgebraicType.createProductType([])),
      new SumTypeVariant("InProgress", AlgebraicType.createProductType([])),
      new SumTypeVariant("Completed", AlgebraicType.createProductType([])),
      new SumTypeVariant("Cancelled", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EventStatus): void {
      EventStatus.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EventStatus {
      return EventStatus.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `EventStatus`.
export type EventStatus = EventStatus.Draft | EventStatus.Published | EventStatus.InProgress | EventStatus.Completed | EventStatus.Cancelled;

export default EventStatus;

