// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { ParticipantRole as __ParticipantRole } from "./participant_role_type";
import { ParticipantStatus as __ParticipantStatus } from "./participant_status_type";

export type EventParticipant = {
  participationId: bigint,
  eventId: bigint,
  groupId: bigint,
  role: __ParticipantRole,
  status: __ParticipantStatus,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EventParticipant {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("participationId", AlgebraicType.createU64Type()),
      new ProductTypeElement("eventId", AlgebraicType.createU64Type()),
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("role", __ParticipantRole.getTypeScriptAlgebraicType()),
      new ProductTypeElement("status", __ParticipantStatus.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EventParticipant): void {
    EventParticipant.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EventParticipant {
    return EventParticipant.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


