// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { EventParticipant } from "./event_participant_type";
import { ParticipantRole as __ParticipantRole } from "./participant_role_type";
import { ParticipantStatus as __ParticipantStatus } from "./participant_status_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `event_participant`.
 *
 * Obtain a handle from the [`eventParticipant`] property on [`RemoteTables`],
 * like `ctx.db.eventParticipant`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.eventParticipant.on_insert(...)`.
 */
export class EventParticipantTableHandle {
  tableCache: TableCache<EventParticipant>;

  constructor(tableCache: TableCache<EventParticipant>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<EventParticipant> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `participationId` unique index on the table `event_participant`,
   * which allows point queries on the field of the same name
   * via the [`EventParticipantParticipationIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.eventParticipant.participationId().find(...)`.
   *
   * Get a handle on the `participationId` unique index on the table `event_participant`.
   */
  participationId = {
    // Find the subscribed row whose `participationId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): EventParticipant | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.participationId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: EventParticipant) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: EventParticipant) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: EventParticipant) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: EventParticipant) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: EventParticipant, newRow: EventParticipant) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: EventParticipant, newRow: EventParticipant) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
