// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EventStatus,
} from "./types";


export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  creatorGroupId: __t.u64().name("creator_group_id"),
  name: __t.string(),
  description: __t.string(),
  startTime: __t.timestamp().name("start_time"),
  endTime: __t.timestamp().name("end_time"),
  ifcEventLink: __t.option(__t.string()).name("ifc_event_link"),
  bannerUrl: __t.option(__t.string()).name("banner_url"),
  get status() {
    return EventStatus;
  },
  createdAt: __t.timestamp().name("created_at"),
  isInternal: __t.bool().name("is_internal"),
  flightFilterMode: __t.option(__t.string()).name("flight_filter_mode"),
  flightFilterBounds: __t.option(__t.string()).name("flight_filter_bounds"),
  showAllFlights: __t.bool().name("show_all_flights"),
});
