// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import ParticipantRole from "./participant_role_type";
import ParticipantStatus from "./participant_status_type";


export default __t.row({
  participationId: __t.u64().primaryKey().name("participation_id"),
  eventId: __t.u64().name("event_id"),
  groupId: __t.u64().name("group_id"),
  get role() {
    return ParticipantRole;
  },
  get status() {
    return ParticipantStatus;
  },
});
