// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type FlightSignup = {
  signupId: bigint,
  subEventId: bigint,
  groupId: bigint,
  departureIcao: string,
  arrivalIcao: string,
  routeDetails: string | undefined,
  callsign: string | undefined,
  aircraftType: string | undefined,
  desiredDepartureTime: Timestamp | undefined,
  desiredArrivalTime: Timestamp | undefined,
  createdAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace FlightSignup {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("signupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("subEventId", AlgebraicType.createU64Type()),
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("departureIcao", AlgebraicType.createStringType()),
      new ProductTypeElement("arrivalIcao", AlgebraicType.createStringType()),
      new ProductTypeElement("routeDetails", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("callsign", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("aircraftType", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("desiredDepartureTime", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
      new ProductTypeElement("desiredArrivalTime", AlgebraicType.createOptionType(AlgebraicType.createTimestampType())),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: FlightSignup): void {
    FlightSignup.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): FlightSignup {
    return FlightSignup.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


