// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signupId: __t.u64().primaryKey().name("signup_id"),
  subEventId: __t.u64().name("sub_event_id"),
  groupId: __t.u64().name("group_id"),
  departureIcao: __t.string().name("departure_icao"),
  arrivalIcao: __t.string().name("arrival_icao"),
  routeDetails: __t.option(__t.string()).name("route_details"),
  callsign: __t.option(__t.string()),
  aircraftType: __t.option(__t.string()).name("aircraft_type"),
  desiredDepartureTime: __t.option(__t.timestamp()).name("desired_departure_time"),
  desiredArrivalTime: __t.option(__t.timestamp()).name("desired_arrival_time"),
  createdAt: __t.timestamp().name("created_at"),
  eventLead: __t.option(__t.identity()).name("event_lead"),
});
