// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type Group = {
  groupId: bigint,
  name: string,
  tag: string,
  description: string,
  ceoIdentity: Identity,
  ifvarbApproved: boolean,
  websiteUrl: string | undefined,
  logoUrl: string | undefined,
  rating: number | undefined,
  color: string | undefined,
  createdAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Group {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("tag", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("ceoIdentity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("ifvarbApproved", AlgebraicType.createBoolType()),
      new ProductTypeElement("websiteUrl", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("logoUrl", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("rating", AlgebraicType.createOptionType(AlgebraicType.createF32Type())),
      new ProductTypeElement("color", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("createdAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Group): void {
    Group.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Group {
    return Group.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


