// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PermissionLevel as __PermissionLevel } from "./permission_level_type";

export type GroupMembership = {
  membershipId: bigint,
  userIdentity: Identity,
  groupId: bigint,
  permissionLevel: __PermissionLevel,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GroupMembership {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("membershipId", AlgebraicType.createU64Type()),
      new ProductTypeElement("userIdentity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("permissionLevel", __PermissionLevel.getTypeScriptAlgebraicType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GroupMembership): void {
    GroupMembership.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GroupMembership {
    return GroupMembership.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


