// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Group", {
  groupId: __t.u64(),
  name: __t.string(),
  tag: __t.string(),
  description: __t.string(),
  ceoIdentity: __t.identity(),
  ifvarbApproved: __t.bool(),
  websiteUrl: __t.option(__t.string()),
  logoUrl: __t.option(__t.string()),
  rating: __t.option(__t.f32()),
  color: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});


