// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PermissionLevel,
} from "./types";


export default __t.row({
  membershipId: __t.u64().primaryKey().name("membership_id"),
  userIdentity: __t.identity().name("user_identity"),
  groupId: __t.u64().name("group_id"),
  get permissionLevel() {
    return PermissionLevel.name("permission_level");
  },
});
