// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ApplicationStatus,
} from "./types";


export default __t.row({
  applicationId: __t.u64().primaryKey().name("application_id"),
  applicantIdentity: __t.identity().name("applicant_identity"),
  name: __t.string(),
  tag: __t.string(),
  description: __t.string(),
  websiteUrl: __t.option(__t.string()).name("website_url"),
  logoUrl: __t.option(__t.string()).name("logo_url"),
  get status() {
    return ApplicationStatus;
  },
  reviewedBy: __t.option(__t.identity()).name("reviewed_by"),
  reviewedAt: __t.option(__t.timestamp()).name("reviewed_at"),
  reviewNote: __t.option(__t.string()).name("review_note"),
  createdGroupId: __t.option(__t.u64()).name("created_group_id"),
  createdAt: __t.timestamp().name("created_at"),
});
