// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { GroupMembership } from "./group_membership_type";
import { PermissionLevel as __PermissionLevel } from "./permission_level_type";

import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `group_membership`.
 *
 * Obtain a handle from the [`groupMembership`] property on [`RemoteTables`],
 * like `ctx.db.groupMembership`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.groupMembership.on_insert(...)`.
 */
export class GroupMembershipTableHandle {
  tableCache: TableCache<GroupMembership>;

  constructor(tableCache: TableCache<GroupMembership>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<GroupMembership> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `membershipId` unique index on the table `group_membership`,
   * which allows point queries on the field of the same name
   * via the [`GroupMembershipMembershipIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.groupMembership.membershipId().find(...)`.
   *
   * Get a handle on the `membershipId` unique index on the table `group_membership`.
   */
  membershipId = {
    // Find the subscribed row whose `membershipId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): GroupMembership | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.membershipId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: GroupMembership) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: GroupMembership) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: GroupMembership) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: GroupMembership) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: GroupMembership, newRow: GroupMembership) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: GroupMembership, newRow: GroupMembership) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
