// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AddGroupMember } from "./add_group_member_reducer.ts";
export { AddGroupMember };
import { AddLiveChatMessage } from "./add_live_chat_message_reducer.ts";
export { AddLiveChatMessage };
import { AddSubEvent } from "./add_sub_event_reducer.ts";
export { AddSubEvent };
import { ClientConnected } from "./client_connected_reducer.ts";
export { ClientConnected };
import { ClientDisconnected } from "./client_disconnected_reducer.ts";
export { ClientDisconnected };
import { CreateEvent } from "./create_event_reducer.ts";
export { CreateEvent };
import { DeleteFlightSignup } from "./delete_flight_signup_reducer.ts";
export { DeleteFlightSignup };
import { DeleteLiveChatMessage } from "./delete_live_chat_message_reducer.ts";
export { DeleteLiveChatMessage };
import { DeleteSubEvent } from "./delete_sub_event_reducer.ts";
export { DeleteSubEvent };
import { EditLiveChatMessage } from "./edit_live_chat_message_reducer.ts";
export { EditLiveChatMessage };
import { InviteGroupToEvent } from "./invite_group_to_event_reducer.ts";
export { InviteGroupToEvent };
import { RegisterGroup } from "./register_group_reducer.ts";
export { RegisterGroup };
import { RemoveGroupMember } from "./remove_group_member_reducer.ts";
export { RemoveGroupMember };
import { RespondToEventInvitation } from "./respond_to_event_invitation_reducer.ts";
export { RespondToEventInvitation };
import { RotateDiscoveryEvent } from "./rotate_discovery_event_reducer.ts";
export { RotateDiscoveryEvent };
import { SetUserProfile } from "./set_user_profile_reducer.ts";
export { SetUserProfile };
import { SignupForFlight } from "./signup_for_flight_reducer.ts";
export { SignupForFlight };
import { UpdateEvent } from "./update_event_reducer.ts";
export { UpdateEvent };
import { UpdateFlightSignup } from "./update_flight_signup_reducer.ts";
export { UpdateFlightSignup };
import { UpdateGroup } from "./update_group_reducer.ts";
export { UpdateGroup };
import { UpdateLiveFlights } from "./update_live_flights_reducer.ts";
export { UpdateLiveFlights };

// Import and reexport all table handle types
import { DiscoveryEventTableHandle } from "./discovery_event_table.ts";
export { DiscoveryEventTableHandle };
import { DiscoveryRotationScheduleTableHandle } from "./discovery_rotation_schedule_table.ts";
export { DiscoveryRotationScheduleTableHandle };
import { EventTableHandle } from "./event_table.ts";
export { EventTableHandle };
import { EventParticipantTableHandle } from "./event_participant_table.ts";
export { EventParticipantTableHandle };
import { FlightSignupTableHandle } from "./flight_signup_table.ts";
export { FlightSignupTableHandle };
import { GroupTableHandle } from "./group_table.ts";
export { GroupTableHandle };
import { GroupMembershipTableHandle } from "./group_membership_table.ts";
export { GroupMembershipTableHandle };
import { LiveChatMessageTableHandle } from "./live_chat_message_table.ts";
export { LiveChatMessageTableHandle };
import { LiveFlightTableHandle } from "./live_flight_table.ts";
export { LiveFlightTableHandle };
import { SubEventTableHandle } from "./sub_event_table.ts";
export { SubEventTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };

// Import and reexport all types
import { DiscoveryEvent } from "./discovery_event_type.ts";
export { DiscoveryEvent };
import { DiscoveryRotationSchedule } from "./discovery_rotation_schedule_type.ts";
export { DiscoveryRotationSchedule };
import { Event } from "./event_type.ts";
export { Event };
import { EventParticipant } from "./event_participant_type.ts";
export { EventParticipant };
import { EventStatus } from "./event_status_type.ts";
export { EventStatus };
import { FlightSignup } from "./flight_signup_type.ts";
export { FlightSignup };
import { Group } from "./group_type.ts";
export { Group };
import { GroupMembership } from "./group_membership_type.ts";
export { GroupMembership };
import { LiveChatMessage } from "./live_chat_message_type.ts";
export { LiveChatMessage };
import { LiveFlight } from "./live_flight_type.ts";
export { LiveFlight };
import { LiveFlightData } from "./live_flight_data_type.ts";
export { LiveFlightData };
import { ParticipantRole } from "./participant_role_type.ts";
export { ParticipantRole };
import { ParticipantStatus } from "./participant_status_type.ts";
export { ParticipantStatus };
import { PermissionLevel } from "./permission_level_type.ts";
export { PermissionLevel };
import { SubEvent } from "./sub_event_type.ts";
export { SubEvent };
import { SubEventData } from "./sub_event_data_type.ts";
export { SubEventData };
import { SubEventType } from "./sub_event_type_type.ts";
export { SubEventType };
import { User } from "./user_type.ts";
export { User };

const REMOTE_MODULE = {
  tables: {
    discovery_event: {
      tableName: "discovery_event",
      rowType: DiscoveryEvent.getTypeScriptAlgebraicType(),
      primaryKey: "eventId",
      primaryKeyInfo: {
        colName: "eventId",
        colType: DiscoveryEvent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    discovery_rotation_schedule: {
      tableName: "discovery_rotation_schedule",
      rowType: DiscoveryRotationSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
      primaryKeyInfo: {
        colName: "scheduledId",
        colType: DiscoveryRotationSchedule.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    event: {
      tableName: "event",
      rowType: Event.getTypeScriptAlgebraicType(),
      primaryKey: "eventId",
      primaryKeyInfo: {
        colName: "eventId",
        colType: Event.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    event_participant: {
      tableName: "event_participant",
      rowType: EventParticipant.getTypeScriptAlgebraicType(),
      primaryKey: "participationId",
      primaryKeyInfo: {
        colName: "participationId",
        colType: EventParticipant.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    flight_signup: {
      tableName: "flight_signup",
      rowType: FlightSignup.getTypeScriptAlgebraicType(),
      primaryKey: "signupId",
      primaryKeyInfo: {
        colName: "signupId",
        colType: FlightSignup.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    group: {
      tableName: "group",
      rowType: Group.getTypeScriptAlgebraicType(),
      primaryKey: "groupId",
      primaryKeyInfo: {
        colName: "groupId",
        colType: Group.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    group_membership: {
      tableName: "group_membership",
      rowType: GroupMembership.getTypeScriptAlgebraicType(),
      primaryKey: "membershipId",
      primaryKeyInfo: {
        colName: "membershipId",
        colType: GroupMembership.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    live_chat_message: {
      tableName: "live_chat_message",
      rowType: LiveChatMessage.getTypeScriptAlgebraicType(),
      primaryKey: "messageId",
      primaryKeyInfo: {
        colName: "messageId",
        colType: LiveChatMessage.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    live_flight: {
      tableName: "live_flight",
      rowType: LiveFlight.getTypeScriptAlgebraicType(),
      primaryKey: "flightId",
      primaryKeyInfo: {
        colName: "flightId",
        colType: LiveFlight.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    sub_event: {
      tableName: "sub_event",
      rowType: SubEvent.getTypeScriptAlgebraicType(),
      primaryKey: "subEventId",
      primaryKeyInfo: {
        colName: "subEventId",
        colType: SubEvent.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    user: {
      tableName: "user",
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: User.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    add_group_member: {
      reducerName: "add_group_member",
      argsType: AddGroupMember.getTypeScriptAlgebraicType(),
    },
    add_live_chat_message: {
      reducerName: "add_live_chat_message",
      argsType: AddLiveChatMessage.getTypeScriptAlgebraicType(),
    },
    add_sub_event: {
      reducerName: "add_sub_event",
      argsType: AddSubEvent.getTypeScriptAlgebraicType(),
    },
    client_connected: {
      reducerName: "client_connected",
      argsType: ClientConnected.getTypeScriptAlgebraicType(),
    },
    client_disconnected: {
      reducerName: "client_disconnected",
      argsType: ClientDisconnected.getTypeScriptAlgebraicType(),
    },
    create_event: {
      reducerName: "create_event",
      argsType: CreateEvent.getTypeScriptAlgebraicType(),
    },
    delete_flight_signup: {
      reducerName: "delete_flight_signup",
      argsType: DeleteFlightSignup.getTypeScriptAlgebraicType(),
    },
    delete_live_chat_message: {
      reducerName: "delete_live_chat_message",
      argsType: DeleteLiveChatMessage.getTypeScriptAlgebraicType(),
    },
    delete_sub_event: {
      reducerName: "delete_sub_event",
      argsType: DeleteSubEvent.getTypeScriptAlgebraicType(),
    },
    edit_live_chat_message: {
      reducerName: "edit_live_chat_message",
      argsType: EditLiveChatMessage.getTypeScriptAlgebraicType(),
    },
    invite_group_to_event: {
      reducerName: "invite_group_to_event",
      argsType: InviteGroupToEvent.getTypeScriptAlgebraicType(),
    },
    register_group: {
      reducerName: "register_group",
      argsType: RegisterGroup.getTypeScriptAlgebraicType(),
    },
    remove_group_member: {
      reducerName: "remove_group_member",
      argsType: RemoveGroupMember.getTypeScriptAlgebraicType(),
    },
    respond_to_event_invitation: {
      reducerName: "respond_to_event_invitation",
      argsType: RespondToEventInvitation.getTypeScriptAlgebraicType(),
    },
    rotate_discovery_event: {
      reducerName: "rotate_discovery_event",
      argsType: RotateDiscoveryEvent.getTypeScriptAlgebraicType(),
    },
    set_user_profile: {
      reducerName: "set_user_profile",
      argsType: SetUserProfile.getTypeScriptAlgebraicType(),
    },
    signup_for_flight: {
      reducerName: "signup_for_flight",
      argsType: SignupForFlight.getTypeScriptAlgebraicType(),
    },
    update_event: {
      reducerName: "update_event",
      argsType: UpdateEvent.getTypeScriptAlgebraicType(),
    },
    update_flight_signup: {
      reducerName: "update_flight_signup",
      argsType: UpdateFlightSignup.getTypeScriptAlgebraicType(),
    },
    update_group: {
      reducerName: "update_group",
      argsType: UpdateGroup.getTypeScriptAlgebraicType(),
    },
    update_live_flights: {
      reducerName: "update_live_flights",
      argsType: UpdateLiveFlights.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.2.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddGroupMember", args: AddGroupMember }
| { name: "AddLiveChatMessage", args: AddLiveChatMessage }
| { name: "AddSubEvent", args: AddSubEvent }
| { name: "ClientConnected", args: ClientConnected }
| { name: "ClientDisconnected", args: ClientDisconnected }
| { name: "CreateEvent", args: CreateEvent }
| { name: "DeleteFlightSignup", args: DeleteFlightSignup }
| { name: "DeleteLiveChatMessage", args: DeleteLiveChatMessage }
| { name: "DeleteSubEvent", args: DeleteSubEvent }
| { name: "EditLiveChatMessage", args: EditLiveChatMessage }
| { name: "InviteGroupToEvent", args: InviteGroupToEvent }
| { name: "RegisterGroup", args: RegisterGroup }
| { name: "RemoveGroupMember", args: RemoveGroupMember }
| { name: "RespondToEventInvitation", args: RespondToEventInvitation }
| { name: "RotateDiscoveryEvent", args: RotateDiscoveryEvent }
| { name: "SetUserProfile", args: SetUserProfile }
| { name: "SignupForFlight", args: SignupForFlight }
| { name: "UpdateEvent", args: UpdateEvent }
| { name: "UpdateFlightSignup", args: UpdateFlightSignup }
| { name: "UpdateGroup", args: UpdateGroup }
| { name: "UpdateLiveFlights", args: UpdateLiveFlights }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addGroupMember(groupId: bigint, userIdentity: Identity, permissionLevel: PermissionLevel) {
    const __args = { groupId, userIdentity, permissionLevel };
    let __writer = new BinaryWriter(1024);
    AddGroupMember.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_group_member", __argsBuffer, this.setCallReducerFlags.addGroupMemberFlags);
  }

  onAddGroupMember(callback: (ctx: ReducerEventContext, groupId: bigint, userIdentity: Identity, permissionLevel: PermissionLevel) => void) {
    this.connection.onReducer("add_group_member", callback);
  }

  removeOnAddGroupMember(callback: (ctx: ReducerEventContext, groupId: bigint, userIdentity: Identity, permissionLevel: PermissionLevel) => void) {
    this.connection.offReducer("add_group_member", callback);
  }

  addLiveChatMessage(groupId: bigint, eventId: bigint, message: string) {
    const __args = { groupId, eventId, message };
    let __writer = new BinaryWriter(1024);
    AddLiveChatMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_live_chat_message", __argsBuffer, this.setCallReducerFlags.addLiveChatMessageFlags);
  }

  onAddLiveChatMessage(callback: (ctx: ReducerEventContext, groupId: bigint, eventId: bigint, message: string) => void) {
    this.connection.onReducer("add_live_chat_message", callback);
  }

  removeOnAddLiveChatMessage(callback: (ctx: ReducerEventContext, groupId: bigint, eventId: bigint, message: string) => void) {
    this.connection.offReducer("add_live_chat_message", callback);
  }

  addSubEvent(eventId: bigint, name: string, description: string | undefined, subEventType: SubEventType, scheduledStartTime: Timestamp, scheduledEndTime: Timestamp, hubIcao: string | undefined, groupFlightDepartureIcao: string | undefined, groupFlightArrivalIcao: string | undefined, groupFlightRoute: string | undefined, notes: string | undefined) {
    const __args = { eventId, name, description, subEventType, scheduledStartTime, scheduledEndTime, hubIcao, groupFlightDepartureIcao, groupFlightArrivalIcao, groupFlightRoute, notes };
    let __writer = new BinaryWriter(1024);
    AddSubEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_sub_event", __argsBuffer, this.setCallReducerFlags.addSubEventFlags);
  }

  onAddSubEvent(callback: (ctx: ReducerEventContext, eventId: bigint, name: string, description: string | undefined, subEventType: SubEventType, scheduledStartTime: Timestamp, scheduledEndTime: Timestamp, hubIcao: string | undefined, groupFlightDepartureIcao: string | undefined, groupFlightArrivalIcao: string | undefined, groupFlightRoute: string | undefined, notes: string | undefined) => void) {
    this.connection.onReducer("add_sub_event", callback);
  }

  removeOnAddSubEvent(callback: (ctx: ReducerEventContext, eventId: bigint, name: string, description: string | undefined, subEventType: SubEventType, scheduledStartTime: Timestamp, scheduledEndTime: Timestamp, hubIcao: string | undefined, groupFlightDepartureIcao: string | undefined, groupFlightArrivalIcao: string | undefined, groupFlightRoute: string | undefined, notes: string | undefined) => void) {
    this.connection.offReducer("add_sub_event", callback);
  }

  onClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_connected", callback);
  }

  removeOnClientConnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_connected", callback);
  }

  onClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("client_disconnected", callback);
  }

  removeOnClientDisconnected(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("client_disconnected", callback);
  }

  createEvent(creatorGroupId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, subEventsData: SubEventData[]) {
    const __args = { creatorGroupId, name, description, startTime, endTime, ifcEventLink, bannerUrl, subEventsData };
    let __writer = new BinaryWriter(1024);
    CreateEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_event", __argsBuffer, this.setCallReducerFlags.createEventFlags);
  }

  onCreateEvent(callback: (ctx: ReducerEventContext, creatorGroupId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, subEventsData: SubEventData[]) => void) {
    this.connection.onReducer("create_event", callback);
  }

  removeOnCreateEvent(callback: (ctx: ReducerEventContext, creatorGroupId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, subEventsData: SubEventData[]) => void) {
    this.connection.offReducer("create_event", callback);
  }

  deleteFlightSignup(signupId: bigint) {
    const __args = { signupId };
    let __writer = new BinaryWriter(1024);
    DeleteFlightSignup.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_flight_signup", __argsBuffer, this.setCallReducerFlags.deleteFlightSignupFlags);
  }

  onDeleteFlightSignup(callback: (ctx: ReducerEventContext, signupId: bigint) => void) {
    this.connection.onReducer("delete_flight_signup", callback);
  }

  removeOnDeleteFlightSignup(callback: (ctx: ReducerEventContext, signupId: bigint) => void) {
    this.connection.offReducer("delete_flight_signup", callback);
  }

  deleteLiveChatMessage(messageId: bigint) {
    const __args = { messageId };
    let __writer = new BinaryWriter(1024);
    DeleteLiveChatMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_live_chat_message", __argsBuffer, this.setCallReducerFlags.deleteLiveChatMessageFlags);
  }

  onDeleteLiveChatMessage(callback: (ctx: ReducerEventContext, messageId: bigint) => void) {
    this.connection.onReducer("delete_live_chat_message", callback);
  }

  removeOnDeleteLiveChatMessage(callback: (ctx: ReducerEventContext, messageId: bigint) => void) {
    this.connection.offReducer("delete_live_chat_message", callback);
  }

  deleteSubEvent(subEventId: bigint) {
    const __args = { subEventId };
    let __writer = new BinaryWriter(1024);
    DeleteSubEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("delete_sub_event", __argsBuffer, this.setCallReducerFlags.deleteSubEventFlags);
  }

  onDeleteSubEvent(callback: (ctx: ReducerEventContext, subEventId: bigint) => void) {
    this.connection.onReducer("delete_sub_event", callback);
  }

  removeOnDeleteSubEvent(callback: (ctx: ReducerEventContext, subEventId: bigint) => void) {
    this.connection.offReducer("delete_sub_event", callback);
  }

  editLiveChatMessage(messageId: bigint, newMessage: string) {
    const __args = { messageId, newMessage };
    let __writer = new BinaryWriter(1024);
    EditLiveChatMessage.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("edit_live_chat_message", __argsBuffer, this.setCallReducerFlags.editLiveChatMessageFlags);
  }

  onEditLiveChatMessage(callback: (ctx: ReducerEventContext, messageId: bigint, newMessage: string) => void) {
    this.connection.onReducer("edit_live_chat_message", callback);
  }

  removeOnEditLiveChatMessage(callback: (ctx: ReducerEventContext, messageId: bigint, newMessage: string) => void) {
    this.connection.offReducer("edit_live_chat_message", callback);
  }

  inviteGroupToEvent(eventId: bigint, invitedGroupId: bigint) {
    const __args = { eventId, invitedGroupId };
    let __writer = new BinaryWriter(1024);
    InviteGroupToEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("invite_group_to_event", __argsBuffer, this.setCallReducerFlags.inviteGroupToEventFlags);
  }

  onInviteGroupToEvent(callback: (ctx: ReducerEventContext, eventId: bigint, invitedGroupId: bigint) => void) {
    this.connection.onReducer("invite_group_to_event", callback);
  }

  removeOnInviteGroupToEvent(callback: (ctx: ReducerEventContext, eventId: bigint, invitedGroupId: bigint) => void) {
    this.connection.offReducer("invite_group_to_event", callback);
  }

  registerGroup(name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined) {
    const __args = { name, tag, description, websiteUrl, logoUrl };
    let __writer = new BinaryWriter(1024);
    RegisterGroup.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("register_group", __argsBuffer, this.setCallReducerFlags.registerGroupFlags);
  }

  onRegisterGroup(callback: (ctx: ReducerEventContext, name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined) => void) {
    this.connection.onReducer("register_group", callback);
  }

  removeOnRegisterGroup(callback: (ctx: ReducerEventContext, name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined) => void) {
    this.connection.offReducer("register_group", callback);
  }

  removeGroupMember(groupId: bigint, userIdentity: Identity) {
    const __args = { groupId, userIdentity };
    let __writer = new BinaryWriter(1024);
    RemoveGroupMember.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("remove_group_member", __argsBuffer, this.setCallReducerFlags.removeGroupMemberFlags);
  }

  onRemoveGroupMember(callback: (ctx: ReducerEventContext, groupId: bigint, userIdentity: Identity) => void) {
    this.connection.onReducer("remove_group_member", callback);
  }

  removeOnRemoveGroupMember(callback: (ctx: ReducerEventContext, groupId: bigint, userIdentity: Identity) => void) {
    this.connection.offReducer("remove_group_member", callback);
  }

  respondToEventInvitation(eventId: bigint, groupId: bigint, response: ParticipantStatus) {
    const __args = { eventId, groupId, response };
    let __writer = new BinaryWriter(1024);
    RespondToEventInvitation.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("respond_to_event_invitation", __argsBuffer, this.setCallReducerFlags.respondToEventInvitationFlags);
  }

  onRespondToEventInvitation(callback: (ctx: ReducerEventContext, eventId: bigint, groupId: bigint, response: ParticipantStatus) => void) {
    this.connection.onReducer("respond_to_event_invitation", callback);
  }

  removeOnRespondToEventInvitation(callback: (ctx: ReducerEventContext, eventId: bigint, groupId: bigint, response: ParticipantStatus) => void) {
    this.connection.offReducer("respond_to_event_invitation", callback);
  }

  rotateDiscoveryEvent(scheduleInfo: DiscoveryRotationSchedule) {
    const __args = { scheduleInfo };
    let __writer = new BinaryWriter(1024);
    RotateDiscoveryEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("rotate_discovery_event", __argsBuffer, this.setCallReducerFlags.rotateDiscoveryEventFlags);
  }

  onRotateDiscoveryEvent(callback: (ctx: ReducerEventContext, scheduleInfo: DiscoveryRotationSchedule) => void) {
    this.connection.onReducer("rotate_discovery_event", callback);
  }

  removeOnRotateDiscoveryEvent(callback: (ctx: ReducerEventContext, scheduleInfo: DiscoveryRotationSchedule) => void) {
    this.connection.offReducer("rotate_discovery_event", callback);
  }

  setUserProfile(displayName: string, ifcProfileUrl: string | undefined, ifcCallsignPrefix: string | undefined, timezone: string | undefined) {
    const __args = { displayName, ifcProfileUrl, ifcCallsignPrefix, timezone };
    let __writer = new BinaryWriter(1024);
    SetUserProfile.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_user_profile", __argsBuffer, this.setCallReducerFlags.setUserProfileFlags);
  }

  onSetUserProfile(callback: (ctx: ReducerEventContext, displayName: string, ifcProfileUrl: string | undefined, ifcCallsignPrefix: string | undefined, timezone: string | undefined) => void) {
    this.connection.onReducer("set_user_profile", callback);
  }

  removeOnSetUserProfile(callback: (ctx: ReducerEventContext, displayName: string, ifcProfileUrl: string | undefined, ifcCallsignPrefix: string | undefined, timezone: string | undefined) => void) {
    this.connection.offReducer("set_user_profile", callback);
  }

  signupForFlight(subEventId: bigint, groupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) {
    const __args = { subEventId, groupId, departureIcao, arrivalIcao, routeDetails, callsign, aircraftType, desiredDepartureTime, desiredArrivalTime };
    let __writer = new BinaryWriter(1024);
    SignupForFlight.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("signup_for_flight", __argsBuffer, this.setCallReducerFlags.signupForFlightFlags);
  }

  onSignupForFlight(callback: (ctx: ReducerEventContext, subEventId: bigint, groupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) => void) {
    this.connection.onReducer("signup_for_flight", callback);
  }

  removeOnSignupForFlight(callback: (ctx: ReducerEventContext, subEventId: bigint, groupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) => void) {
    this.connection.offReducer("signup_for_flight", callback);
  }

  updateEvent(eventId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, status: EventStatus) {
    const __args = { eventId, name, description, startTime, endTime, ifcEventLink, bannerUrl, status };
    let __writer = new BinaryWriter(1024);
    UpdateEvent.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_event", __argsBuffer, this.setCallReducerFlags.updateEventFlags);
  }

  onUpdateEvent(callback: (ctx: ReducerEventContext, eventId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, status: EventStatus) => void) {
    this.connection.onReducer("update_event", callback);
  }

  removeOnUpdateEvent(callback: (ctx: ReducerEventContext, eventId: bigint, name: string, description: string, startTime: Timestamp, endTime: Timestamp, ifcEventLink: string | undefined, bannerUrl: string | undefined, status: EventStatus) => void) {
    this.connection.offReducer("update_event", callback);
  }

  updateFlightSignup(signupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) {
    const __args = { signupId, departureIcao, arrivalIcao, routeDetails, callsign, aircraftType, desiredDepartureTime, desiredArrivalTime };
    let __writer = new BinaryWriter(1024);
    UpdateFlightSignup.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_flight_signup", __argsBuffer, this.setCallReducerFlags.updateFlightSignupFlags);
  }

  onUpdateFlightSignup(callback: (ctx: ReducerEventContext, signupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) => void) {
    this.connection.onReducer("update_flight_signup", callback);
  }

  removeOnUpdateFlightSignup(callback: (ctx: ReducerEventContext, signupId: bigint, departureIcao: string, arrivalIcao: string, routeDetails: string | undefined, callsign: string | undefined, aircraftType: string | undefined, desiredDepartureTime: Timestamp | undefined, desiredArrivalTime: Timestamp | undefined) => void) {
    this.connection.offReducer("update_flight_signup", callback);
  }

  updateGroup(groupId: bigint, name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined, color: string | undefined) {
    const __args = { groupId, name, tag, description, websiteUrl, logoUrl, color };
    let __writer = new BinaryWriter(1024);
    UpdateGroup.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_group", __argsBuffer, this.setCallReducerFlags.updateGroupFlags);
  }

  onUpdateGroup(callback: (ctx: ReducerEventContext, groupId: bigint, name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined, color: string | undefined) => void) {
    this.connection.onReducer("update_group", callback);
  }

  removeOnUpdateGroup(callback: (ctx: ReducerEventContext, groupId: bigint, name: string, tag: string, description: string, websiteUrl: string | undefined, logoUrl: string | undefined, color: string | undefined) => void) {
    this.connection.offReducer("update_group", callback);
  }

  updateLiveFlights(flights: LiveFlightData[]) {
    const __args = { flights };
    let __writer = new BinaryWriter(1024);
    UpdateLiveFlights.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_live_flights", __argsBuffer, this.setCallReducerFlags.updateLiveFlightsFlags);
  }

  onUpdateLiveFlights(callback: (ctx: ReducerEventContext, flights: LiveFlightData[]) => void) {
    this.connection.onReducer("update_live_flights", callback);
  }

  removeOnUpdateLiveFlights(callback: (ctx: ReducerEventContext, flights: LiveFlightData[]) => void) {
    this.connection.offReducer("update_live_flights", callback);
  }

}

export class SetReducerFlags {
  addGroupMemberFlags: CallReducerFlags = 'FullUpdate';
  addGroupMember(flags: CallReducerFlags) {
    this.addGroupMemberFlags = flags;
  }

  addLiveChatMessageFlags: CallReducerFlags = 'FullUpdate';
  addLiveChatMessage(flags: CallReducerFlags) {
    this.addLiveChatMessageFlags = flags;
  }

  addSubEventFlags: CallReducerFlags = 'FullUpdate';
  addSubEvent(flags: CallReducerFlags) {
    this.addSubEventFlags = flags;
  }

  createEventFlags: CallReducerFlags = 'FullUpdate';
  createEvent(flags: CallReducerFlags) {
    this.createEventFlags = flags;
  }

  deleteFlightSignupFlags: CallReducerFlags = 'FullUpdate';
  deleteFlightSignup(flags: CallReducerFlags) {
    this.deleteFlightSignupFlags = flags;
  }

  deleteLiveChatMessageFlags: CallReducerFlags = 'FullUpdate';
  deleteLiveChatMessage(flags: CallReducerFlags) {
    this.deleteLiveChatMessageFlags = flags;
  }

  deleteSubEventFlags: CallReducerFlags = 'FullUpdate';
  deleteSubEvent(flags: CallReducerFlags) {
    this.deleteSubEventFlags = flags;
  }

  editLiveChatMessageFlags: CallReducerFlags = 'FullUpdate';
  editLiveChatMessage(flags: CallReducerFlags) {
    this.editLiveChatMessageFlags = flags;
  }

  inviteGroupToEventFlags: CallReducerFlags = 'FullUpdate';
  inviteGroupToEvent(flags: CallReducerFlags) {
    this.inviteGroupToEventFlags = flags;
  }

  registerGroupFlags: CallReducerFlags = 'FullUpdate';
  registerGroup(flags: CallReducerFlags) {
    this.registerGroupFlags = flags;
  }

  removeGroupMemberFlags: CallReducerFlags = 'FullUpdate';
  removeGroupMember(flags: CallReducerFlags) {
    this.removeGroupMemberFlags = flags;
  }

  respondToEventInvitationFlags: CallReducerFlags = 'FullUpdate';
  respondToEventInvitation(flags: CallReducerFlags) {
    this.respondToEventInvitationFlags = flags;
  }

  rotateDiscoveryEventFlags: CallReducerFlags = 'FullUpdate';
  rotateDiscoveryEvent(flags: CallReducerFlags) {
    this.rotateDiscoveryEventFlags = flags;
  }

  setUserProfileFlags: CallReducerFlags = 'FullUpdate';
  setUserProfile(flags: CallReducerFlags) {
    this.setUserProfileFlags = flags;
  }

  signupForFlightFlags: CallReducerFlags = 'FullUpdate';
  signupForFlight(flags: CallReducerFlags) {
    this.signupForFlightFlags = flags;
  }

  updateEventFlags: CallReducerFlags = 'FullUpdate';
  updateEvent(flags: CallReducerFlags) {
    this.updateEventFlags = flags;
  }

  updateFlightSignupFlags: CallReducerFlags = 'FullUpdate';
  updateFlightSignup(flags: CallReducerFlags) {
    this.updateFlightSignupFlags = flags;
  }

  updateGroupFlags: CallReducerFlags = 'FullUpdate';
  updateGroup(flags: CallReducerFlags) {
    this.updateGroupFlags = flags;
  }

  updateLiveFlightsFlags: CallReducerFlags = 'FullUpdate';
  updateLiveFlights(flags: CallReducerFlags) {
    this.updateLiveFlightsFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get discoveryEvent(): DiscoveryEventTableHandle {
    return new DiscoveryEventTableHandle(this.connection.clientCache.getOrCreateTable<DiscoveryEvent>(REMOTE_MODULE.tables.discovery_event));
  }

  get discoveryRotationSchedule(): DiscoveryRotationScheduleTableHandle {
    return new DiscoveryRotationScheduleTableHandle(this.connection.clientCache.getOrCreateTable<DiscoveryRotationSchedule>(REMOTE_MODULE.tables.discovery_rotation_schedule));
  }

  get event(): EventTableHandle {
    return new EventTableHandle(this.connection.clientCache.getOrCreateTable<Event>(REMOTE_MODULE.tables.event));
  }

  get eventParticipant(): EventParticipantTableHandle {
    return new EventParticipantTableHandle(this.connection.clientCache.getOrCreateTable<EventParticipant>(REMOTE_MODULE.tables.event_participant));
  }

  get flightSignup(): FlightSignupTableHandle {
    return new FlightSignupTableHandle(this.connection.clientCache.getOrCreateTable<FlightSignup>(REMOTE_MODULE.tables.flight_signup));
  }

  get group(): GroupTableHandle {
    return new GroupTableHandle(this.connection.clientCache.getOrCreateTable<Group>(REMOTE_MODULE.tables.group));
  }

  get groupMembership(): GroupMembershipTableHandle {
    return new GroupMembershipTableHandle(this.connection.clientCache.getOrCreateTable<GroupMembership>(REMOTE_MODULE.tables.group_membership));
  }

  get liveChatMessage(): LiveChatMessageTableHandle {
    return new LiveChatMessageTableHandle(this.connection.clientCache.getOrCreateTable<LiveChatMessage>(REMOTE_MODULE.tables.live_chat_message));
  }

  get liveFlight(): LiveFlightTableHandle {
    return new LiveFlightTableHandle(this.connection.clientCache.getOrCreateTable<LiveFlight>(REMOTE_MODULE.tables.live_flight));
  }

  get subEvent(): SubEventTableHandle {
    return new SubEventTableHandle(this.connection.clientCache.getOrCreateTable<SubEvent>(REMOTE_MODULE.tables.sub_event));
  }

  get user(): UserTableHandle {
    return new UserTableHandle(this.connection.clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
