// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type LiveChatMessage = {
  messageId: bigint,
  sender: Identity,
  groupId: bigint,
  eventId: bigint,
  message: string,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace LiveChatMessage {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("messageId", AlgebraicType.createU64Type()),
      new ProductTypeElement("sender", AlgebraicType.createIdentityType()),
      new ProductTypeElement("groupId", AlgebraicType.createU64Type()),
      new ProductTypeElement("eventId", AlgebraicType.createU64Type()),
      new ProductTypeElement("message", AlgebraicType.createStringType()),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: LiveChatMessage): void {
    LiveChatMessage.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): LiveChatMessage {
    return LiveChatMessage.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


