// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("LiveFlightData", {
  flightId: __t.string(),
  callsign: __t.string(),
  aircraftId: __t.string(),
  liveryId: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  altitude: __t.i32(),
  heading: __t.u16(),
  groundSpeed: __t.u16(),
  lastUpdated: __t.timestamp(),
});


