// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  flightId: __t.string().primaryKey().name("flight_id"),
  eventId: __t.option(__t.u64()).name("event_id"),
  subEventId: __t.option(__t.u64()).name("sub_event_id"),
  signupId: __t.option(__t.u64()).name("signup_id"),
  userIdentity: __t.option(__t.identity()).name("user_identity"),
  groupId: __t.option(__t.u64()).name("group_id"),
  callsign: __t.string(),
  aircraftId: __t.string().name("aircraft_id"),
  liveryId: __t.string().name("livery_id"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  altitude: __t.i32(),
  heading: __t.u16(),
  groundSpeed: __t.u16().name("ground_speed"),
  lastUpdated: __t.timestamp().name("last_updated"),
});
