// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type LiveFlightData = {
  flightId: string,
  callsign: string,
  aircraftId: string,
  liveryId: string,
  latitude: number,
  longitude: number,
  altitude: number,
  heading: number,
  groundSpeed: number,
  lastUpdated: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace LiveFlightData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("flightId", AlgebraicType.createStringType()),
      new ProductTypeElement("callsign", AlgebraicType.createStringType()),
      new ProductTypeElement("aircraftId", AlgebraicType.createStringType()),
      new ProductTypeElement("liveryId", AlgebraicType.createStringType()),
      new ProductTypeElement("latitude", AlgebraicType.createF64Type()),
      new ProductTypeElement("longitude", AlgebraicType.createF64Type()),
      new ProductTypeElement("altitude", AlgebraicType.createI32Type()),
      new ProductTypeElement("heading", AlgebraicType.createU16Type()),
      new ProductTypeElement("groundSpeed", AlgebraicType.createU16Type()),
      new ProductTypeElement("lastUpdated", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: LiveFlightData): void {
    LiveFlightData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): LiveFlightData {
    return LiveFlightData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


