// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { SubEventType as __SubEventType } from "./sub_event_type_type";

export type SubEventData = {
  name: string,
  description: string | undefined,
  subEventType: __SubEventType,
  scheduledStartTime: Timestamp,
  scheduledEndTime: Timestamp,
  hubIcao: string | undefined,
  groupFlightDepartureIcao: string | undefined,
  groupFlightArrivalIcao: string | undefined,
  groupFlightRoute: string | undefined,
  notes: string | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SubEventData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("subEventType", __SubEventType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("scheduledStartTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("scheduledEndTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("hubIcao", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("groupFlightDepartureIcao", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("groupFlightArrivalIcao", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("groupFlightRoute", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("notes", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SubEventData): void {
    SubEventData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SubEventData {
    return SubEventData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


