// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import SubEventType from "./sub_event_type_type";


export default __t.row({
  subEventId: __t.u64().primaryKey().name("sub_event_id"),
  eventId: __t.u64().name("event_id"),
  name: __t.string(),
  description: __t.option(__t.string()),
  get subEventType() {
    return SubEventType.name("sub_event_type");
  },
  scheduledStartTime: __t.timestamp().name("scheduled_start_time"),
  scheduledEndTime: __t.timestamp().name("scheduled_end_time"),
  hubIcao: __t.option(__t.string()).name("hub_icao"),
  groupFlightDepartureIcao: __t.option(__t.string()).name("group_flight_departure_icao"),
  groupFlightArrivalIcao: __t.option(__t.string()).name("group_flight_arrival_icao"),
  groupFlightRoute: __t.option(__t.string()).name("group_flight_route"),
  notes: __t.option(__t.string()),
});
