// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DiscoveryEvent = __t.object("DiscoveryEvent", {
  eventId: __t.u64(),
  displayPriority: __t.u64(),
  addedAt: __t.timestamp(),
});
export type DiscoveryEvent = __Infer<typeof DiscoveryEvent>;

export const DiscoveryRotationSchedule = __t.object("DiscoveryRotationSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DiscoveryRotationSchedule = __Infer<typeof DiscoveryRotationSchedule>;

export const Event = __t.object("Event", {
  eventId: __t.u64(),
  creatorGroupId: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  startTime: __t.timestamp(),
  endTime: __t.timestamp(),
  ifcEventLink: __t.option(__t.string()),
  bannerUrl: __t.option(__t.string()),
  get status() {
    return EventStatus;
  },
  createdAt: __t.timestamp(),
  isInternal: __t.bool(),
});
export type Event = __Infer<typeof Event>;

export const EventParticipant = __t.object("EventParticipant", {
  participationId: __t.u64(),
  eventId: __t.u64(),
  groupId: __t.u64(),
  get role() {
    return ParticipantRole;
  },
  get status() {
    return ParticipantStatus;
  },
});
export type EventParticipant = __Infer<typeof EventParticipant>;

// The tagged union or sum type for the algebraic type `EventStatus`.
export const EventStatus = __t.enum("EventStatus", {
  Draft: __t.unit(),
  Published: __t.unit(),
  InProgress: __t.unit(),
  Completed: __t.unit(),
  Cancelled: __t.unit(),
});
export type EventStatus = __Infer<typeof EventStatus>;

export const FlightSignup = __t.object("FlightSignup", {
  signupId: __t.u64(),
  subEventId: __t.u64(),
  groupId: __t.u64(),
  departureIcao: __t.string(),
  arrivalIcao: __t.string(),
  routeDetails: __t.option(__t.string()),
  callsign: __t.option(__t.string()),
  aircraftType: __t.option(__t.string()),
  desiredDepartureTime: __t.option(__t.timestamp()),
  desiredArrivalTime: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
});
export type FlightSignup = __Infer<typeof FlightSignup>;

export const Group = __t.object("Group", {
  groupId: __t.u64(),
  name: __t.string(),
  tag: __t.string(),
  description: __t.string(),
  ceoIdentity: __t.identity(),
  ifvarbApproved: __t.bool(),
  websiteUrl: __t.option(__t.string()),
  logoUrl: __t.option(__t.string()),
  rating: __t.option(__t.f32()),
  color: __t.option(__t.string()),
  createdAt: __t.timestamp(),
});
export type Group = __Infer<typeof Group>;

export const GroupMembership = __t.object("GroupMembership", {
  membershipId: __t.u64(),
  userIdentity: __t.identity(),
  groupId: __t.u64(),
  get permissionLevel() {
    return PermissionLevel;
  },
});
export type GroupMembership = __Infer<typeof GroupMembership>;

export const LiveChatMessage = __t.object("LiveChatMessage", {
  messageId: __t.u64(),
  sender: __t.identity(),
  groupId: __t.u64(),
  eventId: __t.u64(),
  message: __t.string(),
  timestamp: __t.timestamp(),
});
export type LiveChatMessage = __Infer<typeof LiveChatMessage>;

export const LiveFlight = __t.object("LiveFlight", {
  flightId: __t.string(),
  eventId: __t.option(__t.u64()),
  subEventId: __t.option(__t.u64()),
  signupId: __t.option(__t.u64()),
  userIdentity: __t.option(__t.identity()),
  groupId: __t.option(__t.u64()),
  callsign: __t.string(),
  aircraftId: __t.string(),
  liveryId: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  altitude: __t.i32(),
  heading: __t.u16(),
  groundSpeed: __t.u16(),
  lastUpdated: __t.timestamp(),
});
export type LiveFlight = __Infer<typeof LiveFlight>;

export const LiveFlightData = __t.object("LiveFlightData", {
  flightId: __t.string(),
  callsign: __t.string(),
  aircraftId: __t.string(),
  liveryId: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  altitude: __t.i32(),
  heading: __t.u16(),
  groundSpeed: __t.u16(),
  lastUpdated: __t.timestamp(),
});
export type LiveFlightData = __Infer<typeof LiveFlightData>;

// The tagged union or sum type for the algebraic type `ParticipantRole`.
export const ParticipantRole = __t.enum("ParticipantRole", {
  Host: __t.unit(),
  Participant: __t.unit(),
});
export type ParticipantRole = __Infer<typeof ParticipantRole>;

// The tagged union or sum type for the algebraic type `ParticipantStatus`.
export const ParticipantStatus = __t.enum("ParticipantStatus", {
  Pending: __t.unit(),
  Accepted: __t.unit(),
  Declined: __t.unit(),
});
export type ParticipantStatus = __Infer<typeof ParticipantStatus>;

// The tagged union or sum type for the algebraic type `PermissionLevel`.
export const PermissionLevel = __t.enum("PermissionLevel", {
  Member: __t.unit(),
  Staff: __t.unit(),
  Ceo: __t.unit(),
});
export type PermissionLevel = __Infer<typeof PermissionLevel>;

export const SubEvent = __t.object("SubEvent", {
  subEventId: __t.u64(),
  eventId: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  get subEventType() {
    return SubEventType;
  },
  scheduledStartTime: __t.timestamp(),
  scheduledEndTime: __t.timestamp(),
  hubIcao: __t.option(__t.string()),
  groupFlightDepartureIcao: __t.option(__t.string()),
  groupFlightArrivalIcao: __t.option(__t.string()),
  groupFlightRoute: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  eventLead: __t.option(__t.identity()),
});
export type SubEvent = __Infer<typeof SubEvent>;

export const SubEventData = __t.object("SubEventData", {
  name: __t.string(),
  description: __t.option(__t.string()),
  get subEventType() {
    return SubEventType;
  },
  scheduledStartTime: __t.timestamp(),
  scheduledEndTime: __t.timestamp(),
  hubIcao: __t.option(__t.string()),
  groupFlightDepartureIcao: __t.option(__t.string()),
  groupFlightArrivalIcao: __t.option(__t.string()),
  groupFlightRoute: __t.option(__t.string()),
  notes: __t.option(__t.string()),
  eventLead: __t.option(__t.identity()),
});
export type SubEventData = __Infer<typeof SubEventData>;

// The tagged union or sum type for the algebraic type `SubEventType`.
export const SubEventType = __t.enum("SubEventType", {
  FlyIn: __t.unit(),
  FlyOut: __t.unit(),
  GroupFlight: __t.unit(),
});
export type SubEventType = __Infer<typeof SubEventType>;

export const User = __t.object("User", {
  identity: __t.identity(),
  displayName: __t.option(__t.string()),
  ifcProfileUrl: __t.option(__t.string()),
  online: __t.bool(),
  ifcCallsignPrefix: __t.option(__t.string()),
  timezone: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

