// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  EventStatus,
} from "./types";

export default {
  eventId: __t.u64(),
  name: __t.string(),
  description: __t.string(),
  startTime: __t.timestamp(),
  endTime: __t.timestamp(),
  ifcEventLink: __t.option(__t.string()),
  bannerUrl: __t.option(__t.string()),
  get status() {
    return EventStatus;
  },
  isInternal: __t.bool(),
};
