// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  signupId: __t.u64(),
  departureIcao: __t.string(),
  arrivalIcao: __t.string(),
  routeDetails: __t.option(__t.string()),
  callsign: __t.option(__t.string()),
  aircraftType: __t.option(__t.string()),
  liveryId: __t.option(__t.string()),
  eventLead: __t.option(__t.identity()),
  desiredDepartureTime: __t.option(__t.timestamp()),
  desiredArrivalTime: __t.option(__t.timestamp()),
};
