// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SubEventType,
} from "./types";

export default {
  subEventId: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  get subEventType() {
    return SubEventType;
  },
  scheduledStartTime: __t.timestamp(),
  scheduledEndTime: __t.timestamp(),
  eventLead: __t.option(__t.identity()),
  hubIcao: __t.option(__t.string()),
  groupFlightDepartureIcao: __t.option(__t.string()),
  groupFlightArrivalIcao: __t.option(__t.string()),
  groupFlightRoute: __t.option(__t.string()),
  notes: __t.option(__t.string()),
};
