// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  displayName: __t.option(__t.string()).name("display_name"),
  ifcProfileUrl: __t.option(__t.string()).name("ifc_profile_url"),
  online: __t.bool(),
  ifcCallsignPrefix: __t.option(__t.string()).name("ifc_callsign_prefix"),
  timezone: __t.option(__t.string()),
});
