// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCohostToEventReducer from "../add_cohost_to_event_reducer";
import AddEventOverlayReducer from "../add_event_overlay_reducer";
import AddGroupCallsignFilterReducer from "../add_group_callsign_filter_reducer";
import AddGroupMemberReducer from "../add_group_member_reducer";
import AddLiveChatMessageReducer from "../add_live_chat_message_reducer";
import AddSubEventReducer from "../add_sub_event_reducer";
import ApplyForGroupReducer from "../apply_for_group_reducer";
import ApproveGroupApplicationReducer from "../approve_group_application_reducer";
import CreateEventReducer from "../create_event_reducer";
import DeleteEventReducer from "../delete_event_reducer";
import DeleteEventOverlayReducer from "../delete_event_overlay_reducer";
import DeleteFlightSignupReducer from "../delete_flight_signup_reducer";
import DeleteLiveChatMessageReducer from "../delete_live_chat_message_reducer";
import DeleteSubEventReducer from "../delete_sub_event_reducer";
import EditLiveChatMessageReducer from "../edit_live_chat_message_reducer";
import GrantSuperAdminReducer from "../grant_super_admin_reducer";
import InviteGroupToEventReducer from "../invite_group_to_event_reducer";
import RegisterGroupReducer from "../register_group_reducer";
import RejectGroupApplicationReducer from "../reject_group_application_reducer";
import RemoveGroupCallsignFilterReducer from "../remove_group_callsign_filter_reducer";
import RemoveGroupMemberReducer from "../remove_group_member_reducer";
import RemoveParticipantFromEventReducer from "../remove_participant_from_event_reducer";
import RespondToEventInvitationReducer from "../respond_to_event_invitation_reducer";
import RevokeSuperAdminReducer from "../revoke_super_admin_reducer";
import SetGroupDiscordWebhookReducer from "../set_group_discord_webhook_reducer";
import SetUserProfileReducer from "../set_user_profile_reducer";
import SignupForFlightReducer from "../signup_for_flight_reducer";
import UpdateEventReducer from "../update_event_reducer";
import UpdateEventOverlayReducer from "../update_event_overlay_reducer";
import UpdateFlightSignupReducer from "../update_flight_signup_reducer";
import UpdateGroupReducer from "../update_group_reducer";
import UpdateLiveFlightsReducer from "../update_live_flights_reducer";
import UpdateParticipantRoleReducer from "../update_participant_role_reducer";
import UpdateSubEventReducer from "../update_sub_event_reducer";

export type AddCohostToEventParams = __Infer<typeof AddCohostToEventReducer>;
export type AddEventOverlayParams = __Infer<typeof AddEventOverlayReducer>;
export type AddGroupCallsignFilterParams = __Infer<typeof AddGroupCallsignFilterReducer>;
export type AddGroupMemberParams = __Infer<typeof AddGroupMemberReducer>;
export type AddLiveChatMessageParams = __Infer<typeof AddLiveChatMessageReducer>;
export type AddSubEventParams = __Infer<typeof AddSubEventReducer>;
export type ApplyForGroupParams = __Infer<typeof ApplyForGroupReducer>;
export type ApproveGroupApplicationParams = __Infer<typeof ApproveGroupApplicationReducer>;
export type CreateEventParams = __Infer<typeof CreateEventReducer>;
export type DeleteEventParams = __Infer<typeof DeleteEventReducer>;
export type DeleteEventOverlayParams = __Infer<typeof DeleteEventOverlayReducer>;
export type DeleteFlightSignupParams = __Infer<typeof DeleteFlightSignupReducer>;
export type DeleteLiveChatMessageParams = __Infer<typeof DeleteLiveChatMessageReducer>;
export type DeleteSubEventParams = __Infer<typeof DeleteSubEventReducer>;
export type EditLiveChatMessageParams = __Infer<typeof EditLiveChatMessageReducer>;
export type GrantSuperAdminParams = __Infer<typeof GrantSuperAdminReducer>;
export type InviteGroupToEventParams = __Infer<typeof InviteGroupToEventReducer>;
export type RegisterGroupParams = __Infer<typeof RegisterGroupReducer>;
export type RejectGroupApplicationParams = __Infer<typeof RejectGroupApplicationReducer>;
export type RemoveGroupCallsignFilterParams = __Infer<typeof RemoveGroupCallsignFilterReducer>;
export type RemoveGroupMemberParams = __Infer<typeof RemoveGroupMemberReducer>;
export type RemoveParticipantFromEventParams = __Infer<typeof RemoveParticipantFromEventReducer>;
export type RespondToEventInvitationParams = __Infer<typeof RespondToEventInvitationReducer>;
export type RevokeSuperAdminParams = __Infer<typeof RevokeSuperAdminReducer>;
export type SetGroupDiscordWebhookParams = __Infer<typeof SetGroupDiscordWebhookReducer>;
export type SetUserProfileParams = __Infer<typeof SetUserProfileReducer>;
export type SignupForFlightParams = __Infer<typeof SignupForFlightReducer>;
export type UpdateEventParams = __Infer<typeof UpdateEventReducer>;
export type UpdateEventOverlayParams = __Infer<typeof UpdateEventOverlayReducer>;
export type UpdateFlightSignupParams = __Infer<typeof UpdateFlightSignupReducer>;
export type UpdateGroupParams = __Infer<typeof UpdateGroupReducer>;
export type UpdateLiveFlightsParams = __Infer<typeof UpdateLiveFlightsReducer>;
export type UpdateParticipantRoleParams = __Infer<typeof UpdateParticipantRoleReducer>;
export type UpdateSubEventParams = __Infer<typeof UpdateSubEventReducer>;

