// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddGroupMemberReducer from "../add_group_member_reducer";
import AddLiveChatMessageReducer from "../add_live_chat_message_reducer";
import AddSubEventReducer from "../add_sub_event_reducer";
import CreateEventReducer from "../create_event_reducer";
import DeleteEventReducer from "../delete_event_reducer";
import DeleteFlightSignupReducer from "../delete_flight_signup_reducer";
import DeleteLiveChatMessageReducer from "../delete_live_chat_message_reducer";
import DeleteSubEventReducer from "../delete_sub_event_reducer";
import EditLiveChatMessageReducer from "../edit_live_chat_message_reducer";
import InviteGroupToEventReducer from "../invite_group_to_event_reducer";
import RegisterGroupReducer from "../register_group_reducer";
import RemoveGroupMemberReducer from "../remove_group_member_reducer";
import RespondToEventInvitationReducer from "../respond_to_event_invitation_reducer";
import SetUserProfileReducer from "../set_user_profile_reducer";
import SignupForFlightReducer from "../signup_for_flight_reducer";
import UpdateEventReducer from "../update_event_reducer";
import UpdateFlightSignupReducer from "../update_flight_signup_reducer";
import UpdateGroupReducer from "../update_group_reducer";
import UpdateLiveFlightsReducer from "../update_live_flights_reducer";

export type AddGroupMemberParams = __Infer<typeof AddGroupMemberReducer>;
export type AddLiveChatMessageParams = __Infer<typeof AddLiveChatMessageReducer>;
export type AddSubEventParams = __Infer<typeof AddSubEventReducer>;
export type CreateEventParams = __Infer<typeof CreateEventReducer>;
export type DeleteEventParams = __Infer<typeof DeleteEventReducer>;
export type DeleteFlightSignupParams = __Infer<typeof DeleteFlightSignupReducer>;
export type DeleteLiveChatMessageParams = __Infer<typeof DeleteLiveChatMessageReducer>;
export type DeleteSubEventParams = __Infer<typeof DeleteSubEventReducer>;
export type EditLiveChatMessageParams = __Infer<typeof EditLiveChatMessageReducer>;
export type InviteGroupToEventParams = __Infer<typeof InviteGroupToEventReducer>;
export type RegisterGroupParams = __Infer<typeof RegisterGroupReducer>;
export type RemoveGroupMemberParams = __Infer<typeof RemoveGroupMemberReducer>;
export type RespondToEventInvitationParams = __Infer<typeof RespondToEventInvitationReducer>;
export type SetUserProfileParams = __Infer<typeof SetUserProfileReducer>;
export type SignupForFlightParams = __Infer<typeof SignupForFlightReducer>;
export type UpdateEventParams = __Infer<typeof UpdateEventReducer>;
export type UpdateFlightSignupParams = __Infer<typeof UpdateFlightSignupReducer>;
export type UpdateGroupParams = __Infer<typeof UpdateGroupReducer>;
export type UpdateLiveFlightsParams = __Infer<typeof UpdateLiveFlightsReducer>;

